In [6]:
import pandas as pd

import matplotlib.pyplot as plt

In [18]:
data = pd.read_parquet('activity.parquet').reset_index()
# data = pd.read_csv('activity.csv')

data = data.drop(columns=['level_0', 'index', 'isActive', 'sessionId', 'stationName', 'accountName', 'totalCostLocal', 'id', 'accountId'])

In [19]:
data

,energyConsumed,duration,cost,date,rate,name
0,0.00386,8.141,0.000395,2024-02-27 03:31:24,0.0975,Stall # 100
1,46.58587,46958.599,4.769228,2024-03-04 02:59:59,0.0975,Stall # 100
2,37.67717,54864.469,3.857200,2024-03-15 00:30:18,0.0975,Stall # 100
3,39.24104,75723.523,4.017301,2024-03-29 02:13:56,0.0975,Stall # 100
4,9.57428,5613.704,1.049533,2024-04-05 00:31:45,0.1044,Stall # 100
...,...,...,...,...,...,...
10179,49.98066,59064.319,6.134876,2026-08-25 01:49:57,0.1169,Stall # 94
10180,53.15330,70120.959,6.524302,2026-08-31 23:30:24,0.1169,Stall # 94
10181,0.01416,15.096,0.001738,2026-09-07 22:52:22,0.1169,Stall # 94
10182,48.49787,60132.600,5.952871,2026-09-07 22:53:22,0.1169,Stall # 94
10183,43.60786,57821.688,5.352647,2026-09-13 04:58:44,0.1169,Stall # 94

In [85]:
data['member'] = "N/A"

#---Modo---

mask = data['name'] == "Stall # 45"
data.loc[mask, 'member'] = "Modo"

mask = data['name'] == "Stall # 46"
data.loc[mask, 'member'] = "Modo"

#---Modo---

smask = data['name'] == "Stall # 54"
tmask = data['date'] >= "2024-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "215"

smask = data['name'] == "Stall # 55"
tmask = data['date'] >= "2026-08-01"
mask = smask & tmask
data.loc[mask, 'member'] = "215"

smask = data['name'] == "Stall # 66"
tmask = data['date'] >= "2025-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "206"

smask = data['name'] == "Stall # 70"
tmask = data['date'] >= "2026-05-22"
mask = smask & tmask
data.loc[mask, 'member'] = "215"


smask = data['name'] == "Stall # 71"
tmask = data['date'] >= "2024-10-01"
tmask &= data['date'] <= "2026-05-22"
mask = smask & tmask
data.loc[mask, 'member'] = "509"

smask = data['name'] == "Stall # 72"
tmask = data['date'] >= "2024-11-01"
mask = smask & tmask
data.loc[mask, 'member'] = "312"

smask = data['name'] == "Stall # 76"
tmask = data['date'] >= "2024-09-01"
mask = smask & tmask
data.loc[mask, 'member'] = "112"


smask = data['name'] == "Stall # 77"
tmask = data['date'] >= "2024-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "202"

smask = data['name'] == "Stall # 78"
tmask = data['date'] >= "2024-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "416"

smask = data['name'] == "Stall # 82"
tmask = data['date'] >= "2025-04-01"
mask = smask & tmask
data.loc[mask, 'member'] = "302"

smask = data['name'] == "Stall # 87"
tmask = data['date'] >= "2026-05-22"
mask = smask & tmask
data.loc[mask, 'member'] = "216"

smask = data['name'] == "Stall # 93"
tmask = data['date'] >= "2025-07-01"
mask = smask & tmask
data.loc[mask, 'member'] = "320"

smask = data['name'] == "Stall # 94"
tmask = data['date'] < "2026-05-22"
mask = smask & tmask
data.loc[mask, 'member'] = "215"

smask = data['name'] == "Stall # 94"
tmask = data['date'] >= "2025-10-01"
mask = smask & tmask
data.loc[mask, 'member'] = "215"

smask = data['name'] == "Stall # 94"
tmask = data['date'] >= "2026-05-22"
mask = smask & tmask
data.loc[mask, 'member'] = "509"

smask = data['name'] == "Stall # 100"
tmask = data['date'] >= "2024-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "306"

smask = data['name'] == "Stall # 101"
tmask = data['date'] >= "2024-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "418"

smask = data['name'] == "Stall # 106"
tmask = data['date'] >= "2026-01-01"
mask = smask & tmask
data.loc[mask, 'member'] = "317"

smask = data['name'] == "Stall # 107"
tmask = data['date'] >= "2026-08-01"
mask = smask & tmask
data.loc[mask, 'member'] = "502"

smask = data['name'] == "Stall # 113"
tmask = data['date'] >= "2024-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "203"

smask = data['name'] == "Stall # 113"
tmask = data['date'] >= "2024-03-01"
mask = smask & tmask
data.loc[mask, 'member'] = "506"

smask = data['name'] == "Stall # 120"
tmask = data['date'] >= "2025-11-01"
mask = smask & tmask
data.loc[mask, 'member'] = "315"

In [86]:
mask = (data['name'] == "Stall # 71")
data[mask]

,energyConsumed,duration,cost,date,rate,name,member
5819,1.65820,18497.091,0.169758,2024-02-26,0.0975,Stall # 71,N/A
5820,3.21336,48555.747,0.328968,2024-02-27,0.0975,Stall # 71,N/A
5821,15.97772,48913.530,1.635719,2024-02-28,0.0975,Stall # 71,N/A
5822,8.98865,55698.077,0.920213,2024-02-29,0.0975,Stall # 71,N/A
5823,12.46122,77960.864,1.275717,2024-03-01,0.0975,Stall # 71,N/A
...,...,...,...,...,...,...,...
6168,52.23598,86401.291,6.411705,2026-05-06,0.1169,Stall # 71,509
6169,0.00000,5946.734,0.000000,2026-05-07,0.1169,Stall # 71,509
6170,47.79051,67955.849,5.866046,2026-05-17,0.1169,Stall # 71,509
6171,37.77024,62893.026,4.636108,2026-05-19,0.1169,Stall # 71,509
6172,37.55313,22224.149,4.609459,2026-08-22,0.1169,Stall # 71,N/A

In [111]:
data["date"] = data["date"].dt.floor("D")
mask = data['cost'] > 0
mask &= data['date'] >= '2024-03-01'
masked_data = data[mask]

masked_data['duration'] /= 3600.
masked_data.columns = ['usage (kWh)', 'duration (hr)', 'cost ($)', 'month', 'rate', 'name', 'member']
print(masked_data.columns)
    
result = []

for member, member_data in masked_data.groupby("member"):
    print("=================")
    print(f"Member #{member}")
    for charger, charger_data in member_data.groupby("name"):
        print("-------------------")
        print(charger)
        charger_data = charger_data.reset_index()
        charger_data = charger_data.set_index("month")

        charger_data = charger_data.resample("MS").agg(
            {
                "duration (hr)": "sum",
                "usage (kWh)": "sum",
                "cost ($)": "sum",
            }
        )

        charger_data['duration (hr)'] = charger_data['duration (hr)'].round(1)
        charger_data['cost ($)'] = charger_data['cost ($)'].round(2)
        charger_data['usage (kWh)'] = charger_data['usage (kWh)'].round(1)

        print(charger_data)

        if member != "N/A":
            charger_data.to_csv(f"csv/{member}-{charger}.csv")


        charger_data['member'] = member
        charger_data['charger'] = charger
        result.append(charger_data)

result = pd.concat(result).reset_index()

Index(['usage (kWh)', 'duration (hr)', 'cost ($)', 'month', 'rate', 'name',
       'member'],
      dtype='str')
=================
Member #202
-------------------
Stall # 77
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01          243.1        140.0     14.33
2024-04-01          376.0        228.9     25.09
2024-05-01          258.7        176.4     19.34
2024-06-01          304.3        177.8     19.49
2024-07-01          245.2        166.4     18.24
2024-08-01          196.5        165.4     18.13
2024-09-01          300.5        228.7     25.06
2024-10-01          334.9        240.4     26.35
2024-11-01          314.6        215.0     23.57
2024-12-01          271.8        196.2     21.51
2025-01-01          204.7        169.2     18.55
2025-02-01          112.2         94.8     10.40
2025-03-01          212.3        162.5     17.81
2025-04-01          280.8        170.6     20.05
2025-05-01          259.3        109.1     12.82
2025-06-01          276.3        140.9     16.55
2025-07-01           95.1         84.2      9.89
2025-08-01          170.3        123.3     14.48
2025-09-01          184.0        122.6     14.41
2025-10-01          260.3        168.6     19.82
2025-11-01          154.3         95.4     11.21
2025-12-01          199.8        134.1     15.75
2026-01-01          249.2        149.0     17.51
2026-02-01          164.4         97.3     11.43
2026-03-01          235.5        155.8     18.31
2026-04-01          162.7         72.6      8.91
2026-05-01          258.7        117.8     14.46
2026-06-01          195.9        105.7     12.97
2026-07-01          120.1         82.0     10.06
2026-08-01          307.0        179.6     22.04
2026-09-01           95.2         40.6      4.99
=================
Member #206
-------------------
Stall # 66
            duration (hr)  usage (kWh)  cost ($)
month
2025-03-01          155.9        246.2     26.99
2025-04-01          147.2        290.9     34.17
2025-05-01           77.3        262.8     30.88
2025-06-01          104.5        276.9     32.53
2025-07-01           77.1        238.1     27.98
2025-08-01          169.1        336.0     39.48
2025-09-01           92.3        316.1     37.14
2025-10-01          107.9        454.9     53.45
2025-11-01          147.4        421.9     49.57
2025-12-01          171.1        364.9     42.87
2026-01-01           67.3        329.5     38.72
2026-02-01          111.4        345.1     40.55
2026-03-01          136.5        355.8     41.80
2026-04-01           34.5        129.5     15.90
2026-05-01            0.0          0.0      0.00
2026-06-01           14.6         11.8      1.45
=================
Member #215
-------------------
Stall # 54
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01          397.1        207.2     21.21
2024-04-01          452.4        244.1     26.76
2024-05-01          504.2        236.6     25.93
2024-06-01          438.3        344.8     37.80
2024-07-01          413.3        359.3     39.39
2024-08-01          495.5        343.5     37.66
2024-09-01          500.9        329.1     36.07
2024-10-01          453.3        177.0     19.40
2024-11-01          446.5        251.6     27.58
2024-12-01          441.2        211.2     23.15
2025-01-01          451.4        358.2     39.26
2025-02-01          392.6        212.8     23.33
2025-03-01          330.7        147.3     16.14
2025-04-01          474.6        233.7     27.46
2025-05-01          448.3        204.7     24.06
2025-06-01          288.5        125.3     14.72
2025-07-01          334.6        181.9     21.37
2025-08-01          380.9        181.4     21.31
2025-09-01          437.7        237.5     27.90
2025-10-01          434.0        229.3     26.94
2025-11-01          411.8        222.9     26.19
2025-12-01          369.6        157.7     18.52
2026-01-01          422.8        171.2     20.12
2026-02-01          279.7        715.6     84.09
2026-03-01          406.2       1134.7    133.32
2026-04-01          403.7       1622.5    199.16
2026-05-01          496.8       1807.6    221.87
2026-06-01          411.2       1019.3    125.12
2026-07-01          397.6       1426.4    175.08
2026-08-01          129.9        510.3     62.64
-------------------
Stall # 55
            duration (hr)  usage (kWh)  cost ($)
month
2026-08-01          255.9        856.9    105.18
2026-09-01          243.9        814.7    100.00
-------------------
Stall # 70
            duration (hr)  usage (kWh)  cost ($)
month
2026-05-01           79.6        179.9     22.08
2026-06-01          383.5       1359.6    166.89
2026-07-01          331.1       1178.9    144.70
2026-08-01          317.2       1342.7    164.81
2026-09-01          288.1        703.0     86.29
-------------------
Stall # 94
            duration (hr)  usage (kWh)  cost ($)
month
2025-08-01          275.1        986.9    115.95
2025-09-01          408.0       1102.8    129.57
2025-10-01          443.2        697.7     81.98
2025-11-01          508.8       1325.7    155.76
2025-12-01          491.9        961.4    112.96
2026-01-01          447.8       1044.9    122.77
2026-02-01          348.2       1075.7    126.38
2026-03-01          448.6        891.0    104.69
2026-04-01          355.0       1205.4    147.95
2026-05-01           86.3        155.6     19.10
=================
Member #302
-------------------
Stall # 82
            duration (hr)  usage (kWh)  cost ($)
month
2025-04-01          302.8         76.8      9.03
2025-05-01          312.0         81.7      9.60
2025-06-01          252.3         48.6      5.71
2025-07-01          373.9         66.1      7.77
2025-08-01          413.0         65.6      7.70
2025-09-01          413.3         48.7      5.73
2025-10-01          253.1         97.9     11.50
2025-11-01          413.8         81.9      9.62
2025-12-01          346.9        106.9     12.56
2026-01-01          270.3        104.7     12.30
2026-02-01          201.6         73.0      8.58
2026-03-01          335.1        141.1     16.57
2026-04-01          226.5         83.0     10.19
2026-05-01          247.5         80.7      9.90
2026-06-01          412.2         61.4      7.54
2026-07-01          553.9         26.0      3.19
2026-08-01          380.2         60.6      7.44
2026-09-01          232.1         23.7      2.91
=================
Member #306
-------------------
Stall # 100
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01           49.3        123.5     12.64
2024-04-01           56.4        153.7     16.85
2024-05-01           43.6        131.5     14.42
2024-06-01           25.1         86.2      9.45
2024-07-01           28.0         87.4      9.58
2024-08-01           48.3        134.1     14.70
2024-09-01           35.4         91.8     10.06
2024-10-01           55.3        146.8     16.09
2024-11-01           32.3        102.5     11.23
2024-12-01           78.1        197.1     21.61
2025-01-01           51.3        140.0     15.35
2025-02-01           37.1        140.0     15.35
2025-03-01           33.4         99.5     10.91
2025-04-01           21.4         76.2      8.95
2025-05-01           27.5        117.4     13.79
2025-06-01           68.8        188.5     22.15
2025-07-01           40.0        147.1     17.29
2025-08-01           34.4        150.3     17.66
2025-09-01           47.6        174.6     20.51
2025-10-01           41.4        132.4     15.56
2025-11-01           65.6        192.7     22.64
2025-12-01           68.1        190.8     22.42
2026-01-01           68.9        213.7     25.11
2026-02-01           63.3        161.5     18.98
2026-03-01           31.9        105.5     12.40
2026-04-01           40.2        128.2     15.73
2026-05-01           46.5        161.1     19.78
2026-06-01           27.9        109.9     13.49
2026-07-01           90.9        247.1     30.33
2026-08-01           80.0        253.6     31.13
2026-09-01           27.8         94.3     11.57
=================
Member #312
-------------------
Stall # 72
            duration (hr)  usage (kWh)  cost ($)
month
2024-12-01          221.0        239.4     26.24
2025-01-01          180.7        126.9     13.91
2025-02-01          100.0        100.7     11.04
2025-03-01          203.5        230.6     25.28
2025-04-01          179.1        151.5     17.80
2025-05-01          191.5        138.5     16.27
2025-06-01          116.9        127.5     14.99
2025-07-01          269.0        174.1     20.45
2025-08-01          172.2        170.5     20.04
2025-09-01          178.4        124.7     14.65
2025-10-01           69.3         68.9      8.10
2025-11-01          122.6         93.2     10.95
2025-12-01          287.6        228.6     26.86
2026-01-01          158.7        142.1     16.70
2026-02-01          136.1        114.2     13.42
2026-03-01           89.9        144.1     16.93
2026-04-01          156.7        113.5     13.93
2026-05-01          166.0        208.0     25.53
2026-06-01          234.7        116.2     14.27
2026-07-01          336.4        102.2     12.54
2026-08-01          248.6        101.6     12.47
2026-09-01           60.3        122.2     15.00
=================
Member #315
-------------------
Stall # 120
            duration (hr)  usage (kWh)  cost ($)
month
2025-11-01           90.2        238.1     27.97
2025-12-01          100.2        248.9     29.24
2026-01-01           76.9        211.4     24.84
2026-02-01          100.0        222.9     26.19
2026-03-01           67.5        204.9     24.08
2026-04-01           77.2        174.3     21.39
2026-05-01           70.4        161.8     19.86
2026-06-01           74.1        142.9     17.54
2026-07-01           63.5        145.8     17.90
2026-08-01           43.7        131.0     16.07
=================
Member #317
-------------------
Stall # 106
            duration (hr)  usage (kWh)  cost ($)
month
2026-01-01           57.8        150.4     17.67
2026-02-01           62.2        110.6     13.00
2026-03-01          102.9        147.7     17.35
2026-04-01           84.3        263.7     32.37
2026-05-01           89.4        156.6     19.23
2026-06-01          117.7        280.3     34.41
2026-07-01           33.8        114.0     13.99
2026-08-01           57.7         74.8      9.18
2026-09-01           61.3        131.9     16.19
=================
Member #320
-------------------
Stall # 93
            duration (hr)  usage (kWh)  cost ($)
month
2025-07-01          246.0        289.5     34.01
2025-08-01          268.7        309.7     36.39
2025-09-01          285.7        341.3     40.10
2025-10-01          271.6        346.3     40.69
2025-11-01          229.3        341.2     40.08
2025-12-01          264.0        370.0     43.48
2026-01-01          263.6        363.1     42.67
2026-02-01          200.9        294.9     34.65
2026-03-01          218.3        300.8     35.34
2026-04-01          346.7        313.6     38.50
2026-05-01          275.2        301.5     37.01
2026-06-01          250.4        300.4     36.88
2026-07-01          275.8        329.4     40.43
2026-08-01          157.8        249.4     30.61
2026-09-01          150.1        165.4     20.31
=================
Member #416
-------------------
Stall # 78
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01           26.7         52.6      5.38
2024-04-01           42.0        136.6     14.97
2024-05-01           16.5         56.7      6.22
2024-06-01           13.7         56.8      6.22
2024-07-01           20.3        115.8     12.70
2024-08-01            9.3         49.9      5.47
2024-09-01           30.4        169.1     18.54
2024-10-01           22.3        122.5     13.43
2024-11-01           25.9        123.6     13.55
2024-12-01           58.8        111.6     12.23
2025-01-01           35.0        115.7     12.69
2025-02-01           56.1        167.6     18.37
2025-03-01           54.2        130.1     14.26
2025-04-01           99.9         63.3      7.44
2025-05-01           17.5         29.5      3.47
2025-06-01           24.9         72.2      8.48
2025-07-01           15.8         59.5      6.99
2025-08-01           60.9        167.1     19.63
2025-09-01           19.1         56.5      6.63
2025-10-01           19.1         54.8      6.44
2025-11-01           30.2        124.0     14.57
2025-12-01           18.6         56.7      6.67
2026-01-01           87.7        114.6     13.47
2026-02-01           18.4         55.3      6.50
2026-03-01           40.2        108.0     12.69
2026-04-01           61.7        113.5     13.93
2026-05-01           18.0         51.9      6.37
2026-06-01           12.0         56.8      6.98
2026-07-01           32.8         55.9      6.86
2026-08-01           13.5         55.6      6.82
2026-09-01           19.7         61.1      7.50
=================
Member #418
-------------------
Stall # 101
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01          508.1        466.3     47.74
2024-04-01          469.2        374.3     41.03
2024-05-01          357.9        356.8     39.11
2024-06-01          475.4        461.6     50.60
2024-07-01          477.6        446.3     48.93
2024-08-01          483.3        380.5     41.71
2024-09-01          443.2        402.0     44.07
2024-10-01          489.6        378.8     41.52
2024-11-01          540.6        399.1     43.75
2024-12-01          408.5        247.9     27.18
2025-01-01          516.2        292.2     32.04
2025-02-01          412.8        284.5     31.19
2025-03-01          425.1        330.5     36.23
2025-04-01          506.0        302.6     35.56
2025-05-01          366.0        265.2     31.16
2025-06-01          398.3        333.9     39.23
2025-07-01          394.7        309.4     36.36
2025-08-01          309.5        257.1     30.21
2025-09-01          333.8        280.0     32.90
2025-10-01          230.8        324.1     38.08
2025-11-01          270.5        272.9     32.06
2025-12-01          244.3        250.6     29.45
2026-01-01          169.2        202.0     23.74
2026-02-01          234.0        217.4     25.55
2026-03-01          214.1        286.8     33.70
2026-04-01          229.0        273.5     33.57
2026-05-01          235.5        281.8     34.59
2026-06-01          286.4        328.9     40.37
2026-07-01          273.1        221.5     27.19
2026-08-01          251.4        300.8     36.92
2026-09-01          128.6        185.0     22.71
=================
Member #502
-------------------
Stall # 107
            duration (hr)  usage (kWh)  cost ($)
month
2026-08-01          448.5        102.3     12.56
2026-09-01          305.8        108.2     13.28
=================
Member #506
-------------------
Stall # 113
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01           42.0         41.4      4.24
2024-04-01           70.2        144.1     15.80
2024-05-01           20.5         50.8      5.57
2024-06-01           53.2         62.3      6.83
2024-07-01           11.9         16.8      1.84
2024-08-01           46.0        136.0     14.91
2024-09-01           38.5         97.4     10.68
2024-10-01            0.0          0.0      0.00
2024-11-01           17.1         56.0      6.14
2024-12-01           16.7         61.2      6.71
2025-01-01           44.0         57.7      6.33
2025-02-01           24.0         46.8      5.13
2025-03-01            0.0          0.0      0.00
2025-04-01           16.6         62.2      7.31
2025-05-01           15.7         57.7      6.78
2025-06-01           52.4        143.4     16.85
2025-07-01           77.5        110.5     12.98
2025-08-01           54.9        129.8     15.25
2025-09-01           24.0         54.3      6.38
2025-10-01           10.5         62.4      7.34
2025-11-01           34.7        117.8     13.84
2025-12-01           27.4        115.6     13.58
2026-01-01           31.0        100.6     11.82
2026-02-01           16.0         57.5      6.75
2026-03-01           47.0        176.0     20.68
2026-04-01            0.0          0.0      0.00
2026-05-01           46.5        133.5     16.39
2026-06-01           74.3        126.1     15.48
2026-07-01           46.7        133.5     16.39
2026-08-01           91.8        233.4     28.65
2026-09-01           17.6         50.2      6.16
=================
Member #509
-------------------
Stall # 71
            duration (hr)  usage (kWh)  cost ($)
month
2024-10-01          151.1        224.5     24.61
2024-11-01          257.0        269.9     29.58
2024-12-01          177.6        201.4     22.08
2025-01-01          120.1        132.4     14.51
2025-02-01           73.8        104.3     11.43
2025-03-01           98.4        127.1     13.93
2025-04-01           50.3        131.8     15.49
2025-05-01           86.9        167.1     19.63
2025-06-01           77.0        148.3     17.43
2025-07-01           96.5        219.9     25.84
2025-08-01           65.1        129.7     15.24
2025-09-01           75.0        112.8     13.26
2025-10-01           77.1        150.8     17.72
2025-11-01           58.7        167.1     19.63
2025-12-01           82.6        247.1     29.03
2026-01-01          129.5        224.9     26.42
2026-02-01           75.7        141.9     16.67
2026-03-01           98.9        220.6     25.92
2026-04-01           79.5        138.9     17.06
2026-05-01           60.3        137.8     16.91
-------------------
Stall # 94
            duration (hr)  usage (kWh)  cost ($)
month
2026-05-01           39.0         41.9      5.15
2026-06-01           52.9        164.6     20.20
2026-07-01           90.4        170.8     20.97
2026-08-01          111.2        238.5     29.28
2026-09-01           32.8         92.1     11.31
=================
Member #Modo
-------------------
Stall # 45
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01          209.8         70.3      7.20
2024-04-01          210.6        131.9     14.46
2024-05-01          536.7        265.6     29.11
2024-06-01          408.6        275.0     30.15
2024-07-01          341.1        312.2     34.23
2024-08-01          396.9        305.9     33.53
2024-09-01          336.2        241.9     26.52
2024-10-01          472.5        273.6     29.99
2024-11-01          460.1        217.1     23.80
2024-12-01          430.0        392.1     42.98
2025-01-01          452.6        376.2     41.24
2025-02-01          478.5        258.5     28.33
2025-03-01          413.6        276.5     30.31
2025-04-01          441.7        194.5     22.85
2025-05-01          437.8        192.5     22.62
2025-06-01          429.9        262.6     30.85
2025-07-01          451.9        200.8     23.59
2025-08-01          328.9        351.2     41.27
2025-09-01          461.7        336.0     39.48
2025-10-01          505.8        295.4     34.71
2025-11-01          506.0        324.5     38.13
2025-12-01          439.5        303.7     35.69
2026-01-01          489.9        363.9     42.76
2026-02-01          290.2        163.7     19.23
2026-03-01          546.5        257.4     30.25
2026-04-01          440.2        230.3     28.27
2026-05-01          531.6        288.6     35.43
2026-06-01          518.1        244.5     30.01
2026-07-01          379.4        282.2     34.64
2026-08-01          575.0        281.1     34.50
2026-09-01          387.6         96.5     11.84
-------------------
Stall # 46
            duration (hr)  usage (kWh)  cost ($)
month
2024-03-01          104.1        120.5     12.33
2024-04-01          298.2        210.4     23.06
2024-05-01          418.2        163.2     17.89
2024-06-01          514.1        302.0     33.10
2024-07-01          382.3        292.2     32.04
2024-08-01          387.9        304.6     33.39
2024-09-01          395.0        222.2     24.36
2024-10-01          532.6        194.8     21.36
2024-11-01          522.4        309.0     33.87
2024-12-01          452.4        233.4     25.59
2025-01-01          435.3        302.4     33.15

In [122]:
# overpaid/deficit over period
# result = result.reset_index()

temp = result.groupby(['month', 'member']).agg({'cost ($)': 'sum', 'charger': 'count'})
temp['underpaid'] = temp['cost ($)'] - (temp['charger'] * 15.)

temp.groupby('member')['underpaid'].sum()

member
202       48.53
206      273.48
215     2805.61
302     -112.16
306       52.73
312       37.37
315       75.08
317       38.39
320      326.15
416     -149.53
418      643.45
502       -4.16
506     -158.19
509      104.30
Modo     848.35
N/A     -580.47
Name: underpaid, dtype: float64

In [123]:
# average cost per month over last year
mask = result['month'] >= '2025-09-01'
mask &= result['month'] < '2026-09-01'

result[mask].groupby(['member', 'charger']).agg({'cost ($)': 'mean'})

                      cost ($)
member charger
202    Stall # 77    14.740000
206    Stall # 66    32.145000
215    Stall # 54    93.412500
       Stall # 55   105.180000
       Stall # 70   124.620000
       Stall # 94   111.240000
302    Stall # 82     9.593333
306    Stall # 100   20.673333
312    Stall # 72    15.529167
315    Stall # 120   22.508000
317    Stall # 106   19.650000
320    Stall # 93    38.370000
416    Stall # 78     8.994167
418    Stall # 101   32.343333
502    Stall # 107   12.560000
506    Stall # 113   13.108333
509    Stall # 71    20.291111
       Stall # 94    18.900000
Modo   Stall # 45    33.591667
       Stall # 46    26.620833
N/A    Stall # 106    2.553333
       Stall # 71     0.384167

In [120]:
result[mask]['cost ($)'].mean()

np.float64(30.912906403940884)